### ISSUE TITLE
any visualize/swaggerUI implementation for  API list

### ISSUE THREAD

**Issue by yangboz** [fsbraun/djangocms-rest#17]
first off , thanks for this great woks on rest of django-cms. 
and wondering  any visualize/swaggerUI implementation for   those restful API list ?

if could be we will be greatly appreciated.

**Comment by fsbraun** [comment]
@yangboz I agree, just have not come around to it. Any support would be appreciated. Did you take a look at https://www.django-rest-framework.org/topics/documenting-your-api/ ?

**Comment by yangboz** [comment]
> @yangboz I agree, just have not come around to it. Any support would be appreciated. Did you take a look at https://www.django-rest-framework.org/topics/documenting-your-api/ ?

yes, openAPI used fastAPI , I mean  how about django-cms-rest  replicate flask restful, restful-plus alike? any plan on it ?
