### ISSUE TITLE
As a developer I would like to have a HeadlessCmsPluginBase so that I can provide a simple plugin visualization for editors without having to write a plugin template for each of my custom plugins.

### ISSUE THREAD

**Issue by macolo** [fsbraun/djangocms-rest#7]
- As a developer I would like to have a HeadlessCmsPluginBase so that I can provide a simple plugin visualization for editors without having to write a plugin template for each of my custom plugins.
- A default template could show the name of the plugin as well as all fields in a list.

## Solution Example

`plugins/your_custom_plugin/cms_plugins.py` (just an example on how to use HeadlessCMSPluginBase)
```
class CustomHeadingPlugin(HeadlessCMSPluginBase):
    model = models.CustomHeadingPluginModel
    module = 'Layout Helpers'
    name = "My Custom Heading"
    allow_children = False
```

`headless_plugin_base.py`
```
from cms.plugin_base import CMSPluginBase
from django.forms import ModelForm

from . import models


class HeadlessCMSPluginBase(CMSPluginBase):
    render_template = 'headless-plugin-default.html'

    # ModelForm
    def get_form_instance(self, instance):
        class HeadlessGenericForm(ModelForm):
            class Meta:
                model = self.model
                fields='__all__'

        form = HeadlessGenericForm(instance=instance)
        return form

    def render(self, context, instance, placeholder):
        form = self.get_form_instance(instance)
        context = super().render(context, instance, placeholder)
        context.update({
            'form': form,
            'name': self.name
        })
        return context
```

`templates/headless-plugin-default.html`
```
<div class="{{ instance.plugin_type|lower }}">
  <h3>{{ name}} (#{{ instance }})</h3>

  <ul>
  {% for field in form %}
    <li>
        {{ field.label }}: {{ field.value }}
    </li>
  {% endfor %}
  </ul>
</div>
```

**Comment by fsbraun** [comment]
Nice! Thank you! I'd love to even just show the admin form (which might be formatted using fieldsets on the plugin class).

**Comment by fsbraun** [comment]
@macolo Thinking a bit about this proposal, I would potentially go one step further:
* In the core, allow plugins to not have a template for headless configurations
* Instead, display the (read-only) admin form (first fieldset only) using admin styles for the plugin
* Allow plugins to declare exceptions (e.g., text which might as well be displayed immediately)/allow a setting to declare exceptions for plugins (needs no change to existing plugins)

This way, we can have the following:
* The data is organized in accordance to how it appears in the change form.
* Most important fields are shown only (avoid info overflow)
* Custom form widgets are respected, such as for filer

**Comment by macolo** [comment]
that sounds great!
